@startuml
ByteBuf             <|--    AbstractByteBuf

AbstractByteBuf     <|--    AbstractReferenceCountedByteBuf
AbstractByteBuf     <|--    AbstractDerivedByteBuf

AbstractReferenceCountedByteBuf       <|--    CompositeByteBuf
AbstractReferenceCountedByteBuf       <|--    FixedCompositeByteBuf
AbstractReferenceCountedByteBuf       <|--    UnpooledDirectByteBuf
AbstractReferenceCountedByteBuf       <|--    UnpooledHeapByteBuf
AbstractReferenceCountedByteBuf       <|--    UnpooledUnsafeDirectByteBuf
AbstractReferenceCountedByteBuf       <|--    PooledByteBuf

PooledByteBuf <|-- PooledHeapByteBuf
PooledByteBuf <|-- PooledUnsafeDirectByteBuf
PooledByteBuf <|-- PooledDirectByteBuf

AbstractDerivedByteBuf  <|--    DuplicatedByteBuf
DuplicatedByteBuf       <|--    PooledDuplicatedByteBuf
AbstractDerivedByteBuf  <|--    ReadOnlyByteBuf
ReadOnlyByteBuf         <|--    ReadOnlyUnsafeDirectByteBuf
AbstractDerivedByteBuf  <|--    SlicedByteBuf
SlicedByteBuf           <|--    PooledSlicedByteBuf

ByteBuf             <|--    EmptyByteBuf
ByteBuf             <|--    SwappedByteBuf
SwappedByteBuf      <|--    UnsafeDirectSwappedByteBuf
ByteBuf             <|--    WrappedByteBuf

WrappedByteBuf      <|--    AdvancedLeakAwareByteBuf
WrappedByteBuf      <|--    SimpleLeakAwareByteBuf
WrappedByteBuf      <|--    UnreleasableByteBuf
@enduml